### ISSUE TITLE
Doctor consultation module is crashing on the cloud instance.

### ISSUE THREAD

**Issue by sadeekhassan** [myclinic-ng/Emmet-Blue-Ui#133]
![Screenshot (54)](https://user-images.githubusercontent.com/39536463/115163417-e446f880-a0a0-11eb-81b4-28ca0412d9fa.png)

**Comment by Samshal** [comment]
Not good

**Comment by Samshal** [comment]
Turns out 404 ng-includes is what causes these infinite redirects. This has been an issue since 2016.
