### ISSUE TITLE
Doctors should be able to add a profile highlight for patients

### ISSUE THREAD

**Issue by Samshal** [myclinic-ng/Emmet-Blue-Ui#80]
These are prominent information like past medical histories, known conditions, pregnancy status, etc. that are always visible to the doctors.

It should be editable

**Comment by sadeekhassan** [comment]
The data entry for this should read "**Past Medical/Surgical History**" and it should be displayed under the proposed vital signs section in the activities summary of the doctor's consultation panel.

@Samshal
