### ISSUE TITLE
Under Billing Module, Balance recorded from past sales do not reflect on the present day cash balance.

### ISSUE THREAD

**Issue by sadeekhassan** [myclinic-ng/Emmet-Blue-Ui#96]
This is problematic because cashiers can decide not to remit cash recovered from previous pending payments form other days that have already been audited.

**Comment by Samshal** [comment]
I need some clarification on this, please.

Does the cash balance only reflect for payment requests that were generated on the current day, so if there are unfulfilled payment requests from previous days and payments are collected, it doesn't reflect in the total cash balance?

Cash balance should be the sum total of the money you collect on the current day regardless of when the payment requests are made, if this is not the case, then we may have a very huge bug on our hands.

**Comment by sadeekhassan** [comment]
From what I've seen about the report in question. I think we have the bug.

**Comment by Samshal** [comment]
Ok, I'd label it appropriately
